"""Fetch the official Census variable metadata for every ACS table referenced
in code/02_download_data.py and save it as a single merged CSV data
dictionary in documentation/data_dictionaries/.

This is the authoritative record of what each ACS variable code means. It is
regenerated by querying the live Census API metadata endpoint for each table
(https://api.census.gov/data/<vintage>/acs/acs5/groups/<table>.json) rather
than hand-maintained, so it can be re-run if the vintage in
02_download_data.py changes.
"""

from pathlib import Path

import pandas as pd
import requests

VINTAGE = 2024
DATASET = "acs/acs5"
OUTPUT_DIR = Path("documentation/data_dictionaries")
MERGED_PATH = OUTPUT_DIR / "acs_variable_dictionary.csv"

# Every ACS table referenced by SOVI_VARIABLES / QHSEBRDN_CODES in
# 02_download_data.py.
TABLES = [
    "B01001", "B01002", "B02001", "B03003", "B09002", "B11001", "B15003",
    "B17001", "B19001", "B19055", "B19301", "B23001", "B23025",
    "B25001", "B25002", "B25003", "B25024", "B25044", "B25064", "B25070",
    "B25077", "B25091", "B27001", "C16002", "C24010", "C24030",
]


def fetch_table(table):
    url = f"https://api.census.gov/data/{VINTAGE}/{DATASET}/groups/{table}.json"
    resp = requests.get(url, timeout=30)
    assert resp.status_code == 200, f"{table}: HTTP {resp.status_code} from {url}"
    variables = resp.json()["variables"]
    rows = [
        {"table": table, "variable": code, "label": meta["label"], "concept": meta.get("concept")}
        for code, meta in variables.items()
        if code.endswith("E") and not code.endswith(("EA", "MA")) and code != "NAME"
    ]
    rows.sort(key=lambda r: r["variable"])
    return pd.DataFrame(rows)


def main():
    OUTPUT_DIR.mkdir(exist_ok=True)
    tables = {table: fetch_table(table) for table in TABLES}

    column_sets = {tuple(df.columns) for df in tables.values()}
    assert len(column_sets) == 1, (
        f"Tables returned different columns ({column_sets}); "
        "writing per-table files instead of merging so nothing is silently dropped."
    )

    for path in OUTPUT_DIR.glob("*.csv"):
        path.unlink()

    merged = pd.concat(tables.values(), ignore_index=True)
    merged.to_csv(MERGED_PATH, index=False)
    print(f"wrote {MERGED_PATH} ({len(merged)} variables across {len(tables)} tables)")


if __name__ == "__main__":
    main()
